### ISSUE TITLE
parallel calls

### ISSUE THREAD

**Issue by agdolla** [WebReflection/sqlite-tag#1]
Hi!
I use sqlite-tag from expressjs so parallel calls happen and I receive:
SQLITE_ERROR: cannot start a transaction within a transaction

using a mutex from async-mutex solves the problem but I would prefer not to serialize the requests. Is it possible ?
thanks
Gabor

**Comment by WebReflection** [comment]
the code is [pretty simple](https://github.com/WebReflection/sqlite-tag/blob/master/esm/index.js#L26-L37) but not fully optimized for the sqlite3 module case ... this is also a relatively new feature so ... are you invoking `commit` ASAP? What are you doing? what's the scenario? do you need a transaction?

**Comment by agdolla** [comment]
I took a part of your code, so

```
  const insert = transaction();
  points.forEach(point => {
    insert`INSERT INTO ...`
  });
  await insert.commit();
```

I did not see any example on how to use it without transaction.
I've been a happy user of dblite for many years :) thanks for dblite !!! Now in the new project I wanted to try sqlite-tag.

**Comment by agdolla** [comment]
I can't send you a PR now but looking at your code:

```
return t = t.then(() => query(['COMMIT']));
```

could be rewritten as"

```
return t = query(['BEGIN TRANSACTION']).thent.then(() => query(['COMMIT']));
```

**Comment by WebReflection** [comment]
@agdolla the replacement for dblite is [sqlite-tag-spawned](https://github.com/WebReflection/sqlite-tag-spawned#readme), not this one ... if you use the `persistent` option you have dblite but smaller, faster, better, etc.

P.S. and transaction in there works as expected, as all queries are sent at once so concurrency works better than ever

**Comment by WebReflection** [comment]
also if you have many connections to the same db remember to use `timeout: 1000` or some meaningful value otherwise concurrent reads might fail (this is a known SQLite thing, even in wal mode).

**Comment by agdolla** [comment]
ok, thanks for the info!
